### ISSUE TITLE
adding extra "metadata info" to the ro-cates

### ISSUE THREAD

**Issue by kmexter** [emo-bon/metaGOflow-data-products-RO-crate-example#3]
...or to "extra-metadata.json"
In any case, to allow these ro-crates to be used as a source of metadata records (in whatever way that will actually be done), it would be a good idea to copy over some of the key details of the material samples ids, details that are traditionally included in metadata records. Here I am asking about 
- spatial range (will be a point, taken from associated observatory logsheet/ttl file)
- temporal range (will be a single point in time, taken from associated observatory logsheet/ttl file)
- taxonomic range - this one is a difficult one as we have to think about how much taxonomic info to include as metadata, so it will need some thinking

**Comment by cymon** [comment]
> ...or to "extra-metadata.json" In any case, to allow these ro-crates to be used as a source of metadata records (in whatever way that will actually be done), it would be a good idea to copy over some of the key details of the material samples ids, details that are traditionally included in metadata records. Here I am asking about
> 
>     * spatial range (will be a point, taken from associated observatory logsheet/ttl file)

So it's not a range, it's just the lat/long from the Observatory sheet in the env_package?

e.g. 
"37.005639/-7.96925"

>     * temporal range (will be a single point in time, taken from associated observatory logsheet/ttl file)

So again, not a range, but the day the sample was collected: collection_date in env_package?

e.g.  "2021-08-05"

>     * taxonomic range - this one is a difficult one as we have to think about how much taxonomic info to include as metadata, so it will need some thinking

Do we have to specify taxonomic ranks? If so it'd just put Bacteria, Archaea, Eukarya and be done with it :) 
The problem being obviously "microbes < 0.2um" (or whatever the mesh size is) is not a taxonomic rank...
So taxonomially speaking our taxonomic range is the whole of life minus anything bigger than 0.2um...

**Comment by kmexter** [comment]
I am now thinking that we will NOT add this info to the ro-crate-metadata.json file. We do need it for the FE metadata file, but that will be a different file.  so will close this as we will surely have new issues for the IDDAS work we will have to do
